apiVersion: v1
kind: Service
metadata:
  name: opentext-service
  labels:
    env: dev
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: opentext-app
