apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: opentext-deployment
  labels:
    env: prod
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: somepod
        image: nginx
        ports:
        - containerPort: 80
