apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    env: prod
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP
  selector:
    app: nginx-app
