apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: opentext-deployment
  labels:
    env: dev 
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: opentext-app
    spec:
      containers:
      - name: xcontainer
        image: npsoni/opentext
        ports:
        - containerPort: 80
